### ISSUE TITLE
Where is DAC?

### ISSUE THREAD

**Issue by wenzhoulyu** [Ericonaldo/ILSwiss#16]
I'm sorry to bother you. But I can not find the achievement of DAC in your code

**Comment by Ericonaldo** [comment]
Actually, DAC simply uses the 'AIRL' reward type (i.e., log D - log (1-D)), with off-policy update and absorbing states. 
The first two features are already implemented so feel free to compose the hyperparameters to use.

As for the last feature, i.e., the absorbing state, in my experience, it is useless, and most existing open-source repos mentioned DAC simply by its off-policy update feature. 

If you really want to try the absorbing states, just turn off the raise at this [line](https://github.com/Ericonaldo/ILSwiss/blob/main/rlkit/core/base_algorithm.py#L137), and set `wrap_absorbing=True` in the yaml to run. (There could be errors when you run that because from some point of time I never test the `wrap_absorbing` feature as I find it is useless. But, you can try it, and see if it can be run fluently.)

**Comment by wenzhoulyu** [comment]
Thank you for your reply!
